language: ruby
cache: bundler
dist: trusty
rvm:
- 2.5.9
addons:
  postgresql: '9.3'
before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
- export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- psql -c 'create database bc_test;' -U postgres
script:
- bundle exec rake db:migrate RAILS_ENV=test VERBOSE=false
- bundle exec rake db:seed RAILS_ENV=test
- bundle exec rspec -fp -t ~skip spec/
notifications:
  slack:
env:
  - APP_URL=http://www.biblechallenges.com
